### ISSUE TITLE
retrofit-adapters-result nullable body

### ISSUE THREAD

**Issue by xanscale** [skydoves/retrofit-adapters#17]
i have a call that can return an optional body

Using normal retrofit all works correctly
```
@GET("....")
suspend fun getFoo(): Response<Foo>
```

but with this lib i receive KotlinNullPointerException on case of null body
```
@GET("....")
suspend fun getFoo(): Result<Foo?>
```

the problem are inside ResultExtension, why not just return body?

i made a PR https://github.com/skydoves/retrofit-adapters/pull/18

**Comment by skydoves** [comment]
Hey @xanscale, I'm a little bit confused about the terminology. Do you mean the empty body (Code 200 responses, right?)

**Comment by skydoves** [comment]
Additionally, what are the benefits of using a nullable body over the `Unit` type for the empty body?

**Comment by xanscale** [comment]
i have a service that can return body or not, in detail

- 200 with body
- 204 without body

Unit are used when you know that there is no body (or you dont care on it)

**Comment by skydoves** [comment]
@xanscale Btw iIs there a meaningful difference between an empty body and a nobody?

**Comment by xanscale** [comment]
@skydoves response body are OPTIONAL! same call can has response body or not based on USER status.

**Comment by skydoves** [comment]
@xanscale I'm unsure if #18 works well because fundamentally OkHttp doesn't support NULL body yet: https://github.com/square/okhttp/issues/7005. 

And can we build any unit test cases for the nullable body similar to this? https://github.com/skydoves/retrofit-adapters/blob/main/retrofit-adapters-result/src/test/kotlin/com/skydoves/retrofit/adapters/result/ResultCallTest.kt#L87

**Comment by xanscale** [comment]
https://github.com/square/okhttp/issues/7005 is about request body not response body.
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Response.java#L151 response body are always nullable

i will made some tests

**Comment by skydoves** [comment]
@xanscale Thanks for your contribution. It will be contained in the next release!
