### ISSUE TITLE
App Crash on HTTP 422 Unprocessable Entity

### ISSUE THREAD

**Issue by AndroidPoet** [skydoves/retrofit-adapters#19]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- 1.0.5 (https://github.com/skydoves/retrofit-adapters/tree/main/retrofit-adapters-result)
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 Xiaomi  Android 10 
**Describe the Bug:**
App Crashed on Http Exception 422 Unprocessable Entity
Add a clear description about the problem.
it is working with all other Exceptions and got crashed when we throw 422 error code 
exact line for crash i have added a two images 

<img width="1512" alt="Screenshot 2023-03-15 at 2 04 57 PM" src="https://user-images.githubusercontent.com/13647384/225253955-8e45877f-f552-4114-bcb5-4b812373d5c8.png">

<img width="976" alt="Screenshot 2023-03-15 at 2 06 56 PM" src="https://user-images.githubusercontent.com/13647384/225254463-4936722e-4f84-4fb9-bb07-5bfe607e7522.png">

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hey @AndroidPoet, you should check out the parameters data type of your data response model. But do you mean the App should return `Result` instead of occurring a crash?

**Comment by AndroidPoet** [comment]
> Hey @AndroidPoet, you should check out the parameters data type of your data response model. But do you mean the App should return `Result` instead of occurring a crash?

Yes for all other exceptions it is working fine! app crashed on this one only we are not parsing anything yet. it is normal Http exception it should work normally.
