### ISSUE TITLE
Null value in non-null parameter when 204 is received

### ISSUE THREAD

**Issue by PavlosTze** [skydoves/retrofit-adapters#33]
**Please complete the following information:**
- Library Version 1.0.12
- Affected Device(s) All
 
**Describe the Bug:**
I'm using the `EitherCallAdapterFactory` and I have experienced **some crashes** related to bad parsing of the response.
When 204 HTTP Status Code is received meaning **NO_CONTENT**, and my response model is something like `Either<Throwable, List<String>>`, the response is parsed as `Either.Right(null)` but this messes up my code as I have identified the response as non-null so in the below layers of the code I treat the `Either.Right(...)` as non-null.

**Expected Behavior:**

**One of the below solutions:**
1. I would expect when the receiver of the `Either.Right` to be a list, and the response is `NO_CONTENT`, then the response to be parsed as `Either.Right(emptyList())`` and respect the non-nullability of the receiver.
2. I would expect to return an `Either.Left` indicating an error as there was no content to map it to `right` (that's what another library I used in the past did, and it was cleaner)

**Comment by PavlosTze** [comment]
@skydoves Can you please check the above? I think the respective fix should go [here](https://github.com/skydoves/retrofit-adapters/blob/43481e08dc0172e4cab9b8be2a16833f9b7c2e7f/retrofit-adapters-arrow/src/main/kotlin/com/skydoves/retrofit/adapters/arrow/internals/EitherExtension.kt#L38)?

**Comment by skydoves** [comment]
Hey @PavlosTze, apologies for the delayed response. I’m not entirely sure I understand the scenario where the response might be so flexible that the return type varies significantly. In most cases, I’d recommend setting `Unit` as the return type if the HTTP request responds with `NO_CONTENT`.
